server:
  port: 8081
spring:
  application:
    name: Attendance1
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/<your databasename>
    username: <your database password>
    password: <your database password>

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update